version: '2'

services:
  web_app:
    build: .
    command: >
      gunicorn -b 0.0.0.0:9090
      --access-logfile -
      --reload
      "web_app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/web_app'
    ports:
      - '9090:9090'

  postgresql:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5434:5432'

volumes:
  postgresql: