DEBUG=True
SECRET_KEY='base64:l/QPDDliJEA/0p/cyJgaIY8eGmCcXY+fia/D5y52H8c='
SQLALCHEMY_DATABASE_URI='postgresql://postgres:postgres@postgres:5432/flask'
SQLALCHEMY_TRACK_MODIFICATIONS=False
SECURITY_PASSWORD_SALT='base64:l/QPDDliJEA/0p/cyJgaIY8eGmCcXY+fia/D5y52H8c='
SECURITY_REGISTERABLE=True